#!/bin/bash
# =============================================================================
# Turnip VPN — StrongSwan IKEv2/IPsec Server Setup
# Ubuntu 22.04 LTS | Run as root
# Usage: bash install.sh <YOUR_SERVER_IP_OR_DOMAIN>
# =============================================================================

set -e

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'
YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC}  $1"; }
success() { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ── Validate ──────────────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && error "Run as root: sudo bash install.sh <server_ip>"
[[ -z "$1" ]]    && error "Usage: bash install.sh <YOUR_SERVER_IP_OR_DOMAIN>"

SERVER_ADDR="$1"
VPN_SUBNET="10.10.10.0/24"
VPN_POOL_START="10.10.10.10"
VPN_POOL_END="10.10.10.200"
DNS1="1.1.1.1"
DNS2="8.8.8.8"
CERTS_DIR="/etc/ipsec.d"
SECRETS_FILE="/etc/ipsec.secrets"
IPSEC_CONF="/etc/ipsec.conf"
STRONGSWAN_CONF="/etc/strongswan.d/charon-logging.conf"

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║         Turnip VPN — IKEv2/IPsec Server Setup        ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
info "Server address : $SERVER_ADDR"
info "VPN subnet     : $VPN_SUBNET"
info "DNS servers    : $DNS1, $DNS2"
echo ""

# ── 1. System update ──────────────────────────────────────────────────────────
info "Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq
success "System updated"

# ── 2. Install packages ───────────────────────────────────────────────────────
info "Installing StrongSwan and dependencies..."
# Remove iptables-persistent first — it conflicts with ufw on Ubuntu 22.04+
apt-get remove -y -qq iptables-persistent 2>/dev/null || true
apt-get install -y -qq \
    strongswan \
    strongswan-pki \
    libcharon-extra-plugins \
    libcharon-extauth-plugins \
    libstrongswan-extra-plugins \
    libtss2-tcti-tabrmd0 \
    iptables \
    ufw \
    net-tools \
    curl \
    openssl
success "Packages installed"

# ── 3. Certificate Authority ──────────────────────────────────────────────────
info "Generating Certificate Authority..."

mkdir -p /etc/ipsec.d/{cacerts,certs,private}
chmod 700 /etc/ipsec.d/private

# CA private key
ipsec pki --gen --type rsa --size 4096 \
    --outform pem > "${CERTS_DIR}/private/caKey.pem"
chmod 600 "${CERTS_DIR}/private/caKey.pem"

# CA self-signed certificate (10 year validity)
ipsec pki --self --ca \
    --lifetime 3650 \
    --in "${CERTS_DIR}/private/caKey.pem" \
    --type rsa \
    --dn "CN=Turnip VPN CA" \
    --outform pem > "${CERTS_DIR}/cacerts/caCert.pem"

success "CA certificate generated"

# ── 4. Server Certificate ─────────────────────────────────────────────────────
info "Generating server certificate for ${SERVER_ADDR}..."

# Server private key
ipsec pki --gen --type rsa --size 4096 \
    --outform pem > "${CERTS_DIR}/private/serverKey.pem"
chmod 600 "${CERTS_DIR}/private/serverKey.pem"

# Server CSR + sign with CA
ipsec pki --pub \
    --in "${CERTS_DIR}/private/serverKey.pem" \
    --type rsa | \
ipsec pki --issue \
    --lifetime 1825 \
    --cacert "${CERTS_DIR}/cacerts/caCert.pem" \
    --cakey "${CERTS_DIR}/private/caKey.pem" \
    --dn "CN=${SERVER_ADDR}" \
    --san "${SERVER_ADDR}" \
    --flag serverAuth \
    --flag ikeIntermediate \
    --outform pem > "${CERTS_DIR}/certs/serverCert.pem"

success "Server certificate generated"

# ── 5. ipsec.conf ─────────────────────────────────────────────────────────────
info "Writing /etc/ipsec.conf..."

cat > "${IPSEC_CONF}" << EOF
# Turnip VPN — ipsec.conf
# Generated by install.sh on $(date)

config setup
    charondebug="ike 1, knl 1, cfg 0"
    uniqueids=no

conn %default
    ikelifetime=60m
    keylife=20m
    rekeymargin=3m
    keyingtries=1
    keyexchange=ikev2

conn turnip
    left=%any
    leftid=${SERVER_ADDR}
    leftauth=pubkey
    leftcert=serverCert.pem
    leftsendcert=always
    leftsubnet=0.0.0.0/0

    right=%any
    rightid=%any
    rightauth=eap-mschapv2
    rightsourceip=${VPN_SUBNET}
    rightdns=${DNS1},${DNS2}

    eap_identity=%identity
    ike=aes256gcm16-sha384-prfsha384-ecp384,aes256-sha256-modp2048,aes256-sha1-modp2048!
    esp=aes256gcm16,aes256-sha256,aes256-sha1!

    dpdaction=clear
    dpddelay=300s
    rekey=no
    leftfirewall=yes
    auto=add
EOF

success "ipsec.conf written"

# ── 6. ipsec.secrets (template) ───────────────────────────────────────────────
info "Writing /etc/ipsec.secrets..."

# Generate a strong random password for the first user
FIRST_PASS=$(openssl rand -base64 16 | tr -dc 'A-Za-z0-9!@#$' | head -c 20)
FIRST_USER="vpnadmin"

cat > "${SECRETS_FILE}" << EOF
# Turnip VPN — ipsec.secrets
# Generated by install.sh on $(date)
#
# Format: <username> : EAP "<password>"
# Add one line per VPN user. Reload with: ipsec secrets

: RSA serverKey.pem

${FIRST_USER} : EAP "${FIRST_PASS}"
EOF

chmod 600 "${SECRETS_FILE}"
success "ipsec.secrets written (first user: ${FIRST_USER})"

# ── 7. StrongSwan charon logging ──────────────────────────────────────────────
info "Configuring charon logging..."

mkdir -p "$(dirname ${STRONGSWAN_CONF})"
cat > "${STRONGSWAN_CONF}" << 'EOF'
charon {
    filelog {
        charon {
            path = /var/log/charon.log
            time_format = %b %e %T
            ike_name = yes
            append = no
            default = 1
            flush_line = yes
        }
        stderr {
            ike = 1
            knl = 3
            default = 1
        }
    }
    syslog {
        identifier = charon-custom
        daemon {
        }
        auth {
            default = -1
            ike = 0
        }
    }
}
EOF

success "Charon logging configured → /var/log/charon.log"

# ── 8. Kernel IP forwarding ───────────────────────────────────────────────────
info "Enabling IP forwarding..."

# Persist across reboots
cat > /etc/sysctl.d/99-vpn.conf << 'EOF'
net.ipv4.ip_forward = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.all.rp_filter = 0
net.ipv6.conf.all.forwarding = 1
net.ipv6.conf.default.forwarding = 1
EOF

sysctl -p /etc/sysctl.d/99-vpn.conf > /dev/null 2>&1
success "IP forwarding enabled"

# ── 9. IPTables / NAT ─────────────────────────────────────────────────────────
info "Configuring iptables NAT and firewall rules..."

# Detect primary network interface
PRIMARY_IFACE=$(ip route show default | awk '/default/ {print $5}' | head -1)
info "Primary interface detected: ${PRIMARY_IFACE}"

# Flush existing NAT rules (preserve INPUT/FORWARD for safety)
iptables -t nat -F

# NAT: masquerade VPN traffic out the primary interface
iptables -t nat -A POSTROUTING -s "${VPN_SUBNET}" -o "${PRIMARY_IFACE}" -m policy --dir out --pol ipsec -j ACCEPT
iptables -t nat -A POSTROUTING -s "${VPN_SUBNET}" -o "${PRIMARY_IFACE}" -j MASQUERADE

# Allow forwarding for VPN subnet
iptables -A FORWARD -s "${VPN_SUBNET}" -j ACCEPT
iptables -A FORWARD -d "${VPN_SUBNET}" -j ACCEPT

# Allow IKE + IPsec on INPUT
iptables -A INPUT -p udp --dport 500 -j ACCEPT
iptables -A INPUT -p udp --dport 4500 -j ACCEPT
iptables -A INPUT -p esp -j ACCEPT
iptables -A INPUT -p ah -j ACCEPT

# Persist rules across reboots without iptables-persistent
mkdir -p /etc/iptables
iptables-save > /etc/iptables/rules.v4
# Restore on boot via a simple systemd unit
cat > /etc/systemd/system/iptables-restore.service << 'UNIT'
[Unit]
Description=Restore iptables rules
Before=network-pre.target
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=/sbin/iptables-restore /etc/iptables/rules.v4
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
UNIT
systemctl enable iptables-restore.service > /dev/null 2>&1
success "iptables rules applied and saved"

# ── 10. UFW ──────────────────────────────────────────────────────────────────
info "Configuring UFW firewall..."

# CRITICAL: UFW sets DEFAULT_FORWARD_POLICY=DROP which blocks VPN traffic
# forwarding even when net.ipv4.ip_forward=1 and iptables FORWARD rules are set.
# Must be ACCEPT so VPN clients can reach the internet through the server.
sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw
info "UFW forward policy set to ACCEPT"

# Inject NAT masquerade into UFW's before.rules so it persists across 'ufw reload'
UFW_BEFORE=/etc/ufw/before.rules
if ! grep -q 'TURNIP-NAT' "${UFW_BEFORE}" 2>/dev/null; then
    sed -i "1s|^|# TURNIP-NAT\n*nat\n:POSTROUTING ACCEPT [0:0]\n-A POSTROUTING -s ${VPN_SUBNET} -o ${PRIMARY_IFACE} -j MASQUERADE\nCOMMIT\n\n|" "${UFW_BEFORE}"
    info "NAT MASQUERADE injected into UFW before.rules"
fi

# Ensure OpenSSH is allowed before enabling to avoid lockout
ufw allow OpenSSH
ufw allow 500/udp
ufw allow 4500/udp
ufw --force enable
success "UFW rules applied"

# ── 11. Start StrongSwan ──────────────────────────────────────────────────────
info "Starting StrongSwan..."
systemctl enable strongswan-starter > /dev/null 2>&1
# Clear stale PID files that block restart on re-runs
systemctl stop strongswan-starter 2>/dev/null || true
rm -f /var/run/charon.pid /var/run/starter.charon.pid /var/lock/subsys/ipsec
sleep 1
systemctl start strongswan-starter
sleep 2

if systemctl is-active --quiet strongswan-starter; then
    success "StrongSwan is running"
else
    error "StrongSwan failed to start. Check: journalctl -u strongswan-starter -n 50"
fi

# ── 12. Export CA cert for clients ───────────────────────────────────────────
CLIENT_CA="/root/turnip-ca.pem"
cp "${CERTS_DIR}/cacerts/caCert.pem" "${CLIENT_CA}"
success "CA cert exported to ${CLIENT_CA} (install this on client devices)"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║                  SETUP COMPLETE ✓                        ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BOLD}Server address :${NC} ${SERVER_ADDR}"
echo -e "${BOLD}VPN type       :${NC} IKEv2 / IPsec / EAP-MSCHAPv2"
echo -e "${BOLD}Subnet         :${NC} ${VPN_SUBNET}"
echo ""
echo -e "${BOLD}First VPN user :${NC}"
echo -e "  Username : ${CYAN}${FIRST_USER}${NC}"
echo -e "  Password : ${CYAN}${FIRST_PASS}${NC}"
echo ""
echo -e "${BOLD}CA cert for clients :${NC} ${CLIENT_CA}"
echo -e "  → Copy to client devices for certificate trust"
echo ""
echo -e "${BOLD}Manage users:${NC}"
echo -e "  Add user  : bash /opt/turnip/adduser.sh <username> <password>"
echo -e "  Del user  : bash /opt/turnip/deluser.sh <username>"
echo -e "  List users: bash /opt/turnip/listusers.sh"
echo ""
echo -e "${BOLD}Useful commands:${NC}"
echo -e "  ipsec status          — active connections"
echo -e "  ipsec statusall       — full tunnel detail"
echo -e "  ipsec restart         — restart daemon"
echo -e "  ipsec secrets         — reload users without restart"
echo -e "  tail -f /var/log/charon.log — live connection log"
echo ""
